# Generated by Django 5.0 on 2023-12-26 18:55

import django.db.models.deletion
import model.models.temporary_password
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("model", "0004_alter_user_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="TemporaryPassword",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "password",
                    models.CharField(
                        default=model.models.temporary_password.generate_token,
                        max_length=43,
                    ),
                ),
                (
                    "for_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
