# Generated by Django 4.2 on 2023-12-28 14:14

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import model.models.temporary_password
import utils.model
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("model", "0005_temporarypassword"),
    ]

    operations = [
        migrations.CreateModel(
            name="CafeTelephone",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("number", models.CharField(max_length=10)),
                ("details", models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={"verbose_name": "cafe_telephone", "db_table": "cafe_telephones",},
            bases=(models.Model, utils.model.JsonModel, utils.model.SoftDeleteModel),
        ),
        migrations.CreateModel(
            name="CafeWorkingHours",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "day_of_week",
                    models.CharField(
                        choices=[
                            ("0", "Sunday"),
                            ("1", "Monday"),
                            ("2", "Tuesday"),
                            ("3", "Wednesday"),
                            ("4", "Thursday"),
                            ("5", "Friday"),
                            ("6", "Saturday"),
                        ],
                        max_length=1,
                    ),
                ),
                ("start", models.TimeField()),
                ("end", models.DurationField()),
            ],
            options={
                "verbose_name": "cafe_working_hours",
                "db_table": "cafe_working_hours",
                "ordering": ("day_of_week",),
            },
            bases=(models.Model, utils.model.JsonModel, utils.model.SoftDeleteModel),
        ),
        migrations.AlterModelOptions(
            name="temporarypassword", options={"verbose_name": "temporary_password"},
        ),
        migrations.AddField(
            model_name="temporarypassword",
            name="expired",
            field=models.DateTimeField(
                default=model.models.temporary_password.exp_time
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="profile_picture",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name="temporarypassword", table="temporary_passwords",
        ),
        migrations.CreateModel(
            name="CafeReview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("review", models.TextField(blank=True, null=True)),
                ("pictures", models.JSONField(blank=True, default=[], null=True)),
                (
                    "rating",
                    models.DecimalField(decimal_places=1, default=0, max_digits=2),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"verbose_name": "cafe_review", "db_table": "cafe_reviews",},
            bases=(models.Model, utils.model.JsonModel, utils.model.SoftDeleteModel),
        ),
        migrations.CreateModel(
            name="Cafe",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(default="", max_length=150)),
                ("details", models.TextField(blank=True, null=True)),
                (
                    "latitude",
                    models.DecimalField(
                        decimal_places=7, default=Decimal("18.7942459"), max_digits=10
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        decimal_places=7, default=Decimal("98.9564772"), max_digits=10
                    ),
                ),
                ("address", models.TextField(blank=True, null=True)),
                ("reviews", models.ManyToManyField(to="model.cafereview")),
                ("telephones", models.ManyToManyField(to="model.cafetelephone")),
                ("working_hours", models.ManyToManyField(to="model.cafeworkinghours")),
            ],
            options={"verbose_name": "cafe", "db_table": "cafes",},
            bases=(models.Model, utils.model.JsonModel, utils.model.SoftDeleteModel),
        ),
    ]
