# Generated by Django 4.2 on 2023-12-28 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("model", "0006_cafetelephone_cafeworkinghours_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cafereview",
            name="pictures",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
