# Generated by Django 4.2 on 2024-01-05 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("model", "0007_alter_cafereview_pictures"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="details_status",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="name",
            field=models.CharField(default="", max_length=70),
        ),
        migrations.AlterUniqueTogether(name="user", unique_together={("email",)},),
    ]
