# Generated by Django 4.1.1 on 2024-01-22 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0008_user_details_status_user_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True),
        ),
    ]
