# Generated by Django 4.1 on 2024-02-21 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0009_cafe_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.TextField(blank=True, null=True),
        ),
    ]
