# Generated by Django 4.2 on 2024-03-04 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0010_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='picture',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cafe',
            name='tags',
            field=models.TextField(blank=True, null=True),
        ),
    ]
